version: '3.8'

services:
  gateway:
    build: 
      context: ./gateway
      dockerfile: ../Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - WHATSAPP_CORE_URL=http://whatsapp-core:4000
    depends_on:
      - whatsapp-core
    restart: unless-stopped

  whatsapp-core:
    build: 
      context: ./whatsapp-core
      dockerfile: ../Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./whatsapp-core:/app
      - /app/node_modules
      - ./whatsapp-core/sessions:/app/sessions
    environment:
      - NODE_ENV=development
      - PORT=4000
    restart: unless-stopped

networks:
  default:
    name: whatsapp-network
